{
 "title": "ADS-B Overview v1",
 "description": "Provides a real-time overview of flights, including total airborne aircraft, flight details, emergency squawk events, and specific airline activity for Easyjet, Ryanair, and Jet2. Useful for monitoring current flight operations.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Flights",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"adsb2otel\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# ✈️ ADS-B Overview\n\nWelcome aboard! This dashboard visualizes real-time flight data sourced from the **dump1090-fa JSON feed** via [adsb2otel](https://github.com/burnettdev/adsb2otel), which is parsed and streamed via OpenTelemetry to your backend database as structured log messages.\n\nEach aircraft's latest position is extracted and displayed on the **GeoMap panel**, allowing you to track live flights with up-to-date coordinates and metadata.\n\n🚦 Active flights are determined by recent log activity — if a flight has transmitted in the past few minutes, it's considered \\\"active\\\" and will appear in counts and visualizations.\n\nStay tuned for altitude shifts, heading changes, and airspace action — all updated as it happens"
   }
  },
  {
   "title": "Current Flight Details",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"adsb2otel\"} |= `` | json | nav_altitude_mcp != ``"
    }
   ]
  },
  {
   "title": "Current Count of Aircraft",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count by(flight) (rate({service_name=\"adsb2otel\"} | json | flight != `` [$__auto])))"
    }
   ]
  },
  {
   "title": "'7700' Squawk Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count by(flight) (rate({service_name=\"adsb2otel\"} | json | squawk = `7700` [$__auto])))"
    }
   ]
  },
  {
   "title": "Easyjet Flights",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count by(flight) (rate({service_name=\"adsb2otel\"} |= `EZY` | json [$__auto])))"
    }
   ]
  },
  {
   "title": "Ryanair Flights",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count by(flight) (rate({service_name=\"adsb2otel\"} |= `RYR` | json [$__auto])))"
    }
   ]
  },
  {
   "title": "Jet2 Flights",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count by(flight) (rate({service_name=\"adsb2otel\"} |= `EXS` | json [$__auto])))"
    }
   ]
  }
 ]
}